services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: push_poc
      MYSQL_USER: test
      MYSQL_PASSWORD: my-secret-pw
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    restart: always
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    ports:
      - 4040:4040
    environment:
      NGROK_AUTHTOKEN: $AUTH_TOKEN
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml

volumes:
  mysql: {}
